#!/bin/bash -e

OUT1="out1"
OUT2="out2"

function do_test {
  for f in `find $1 -name *.*`; do

    if ! ../src/dolmen $f > $OUT1; then
      echo -e "\e[1;31m[KO]\e[0m $1 (regular - $f)"
      return 1
    fi
    if ! ../src/dolmen --interactive $f > $OUT2; then
      echo -e "\e[1;31m[KO]\e[0m $1 (interactive - $f)"
      return 1
    fi
    if ! cmp --quiet $OUT1 $OUT2; then
      echo -e "\e[1;31m[KO]\e[0m $1 (diff - $f), see file $OUT1 and $OUT2"
      return 1
    fi
  done
  echo -e "\e[32m[OK]\e[0m $1"
}

# Test every language
do_test dimacs
do_test smtlib
do_test tptp
do_test zf

# Cleanup temp files
rm -rf $OUT1 $OUT2

