(lang dune 3.0)
(using dune_site 0.1)

(generate_opam_files false)

(package
  (name dolmen-typing-extension-abs-real-split)
  (depends dolmen_type dolmen_loop))

(package
  (name dolmen-model-extension-abs-real-split)
  (depends dolmen-typing-extension-abs-real-split dolmen_model))
