# Main tests
# ==========
# Build dolmen with makefiles and run the testsuite
name: test

# Configure when to run the workflows. Currently only when
# it affects the `master` branch (either pushes to the branch,
# or pull request against it).
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Main workflow
  # =============
  # Build:
  # - the package,
  # - the doc and push it to gh-pages
  # - the examples and push them to the master branch
  test:

    runs-on: ${{ matrix.os }}

    # Build Matrix
    # --------------
    strategy:
      # Do not cancel other jobs when one fails
      fail-fast: false

      matrix:
        # Operating system to run tests on.
        os:
          - ubuntu-latest

        # Ocaml version to test
        ocaml-version:
          - ocaml-base-compiler.4.14.0

    # Build ENV
    # ---------
    env:
      # Ensure opam will not stop because it waits on some user input
      OPAMYES: "true"

    # Build/test steps
    # ----------------
    steps:
    # checkout the repo (full clone, necessary for push later)
    - name: Checkout the repo
      uses: actions/checkout@v3
    # Setup ocaml/opam
    - name: Setup ocaml/opam
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
    # Run opam udpate to get an up-to-date repo
    - name: Update opam repo
      run: opam update
    # Install ocaml deps
    - name: Install Ocaml deps
      run: opam install . --deps-only --with-doc --with-test
    # Build the package
    - name: Build the package
      run: opam exec -- make
    # Check the doc builds
    - name: Build the doc
      run: opam exec -- make doc
    # Check the tests
    - name: Build the examples
      run: opam exec -- make test

    # Update the doc
    # --------------
    - name: Deploy the dev documentation
      uses: JamesIves/github-pages-deploy-action@4.1.1
      if: github.ref == 'refs/heads/master'
      with:
        branch: gh-pages
        folder: _build/default/_doc/_html
        target-folder: dev

